CREATE TABLE IF NOT EXISTS vendor_cutoff_settings (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  vendor_id VARCHAR(36) NOT NULL UNIQUE,
  cutoff_hour INT NOT NULL DEFAULT 17,
  cutoff_minute INT NOT NULL DEFAULT 0,
  is_enabled INT NOT NULL DEFAULT 1,
  reminder_message VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
